# Generated by Django 5.2 on 2025-05-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Transport", "Transport"),
                    ("Shopping", "Shopping"),
                    ("Utilities", "Utilities"),
                    ("Health", "Health"),
                    ("Other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
