# Generated by Django 5.2 on 2025-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
