# Generated by Django 5.2 on 2025-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_balance_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="balance",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
    ]
