# Generated by Django 5.2 on 2025-05-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0008_buget"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
