# Generated by Django 5.2 on 2025-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0009_delete_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="Transactin_type",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
