# Generated by Django 5.2 on 2025-05-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0010_balance_transactin_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="total_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
