# Generated by Django 5.2 on 2025-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0012_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="buget",
            name="monthly_set",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
