# Generated by Django 5.2 on 2025-05-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0013_buget_monthly_set"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balance",
            old_name="balance",
            new_name="transaction_made",
        ),
    ]
