# Generated by Django 5.2 on 2025-05-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0014_rename_balance_balance_transaction_made"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balance",
            old_name="transaction_made",
            new_name="balance",
        ),
    ]
