# Generated by Django 5.2 on 2025-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0015_rename_transaction_made_balance_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
