# Generated by Django 5.2 on 2025-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0016_alter_transaction_amount_alter_transaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="buget",
            name="last_alert_level",
            field=models.IntegerField(default=0),
        ),
    ]
