# Generated by Django 5.2 on 2025-05-30 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0017_buget_last_alert_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="buget",
            name="last_reset",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
