# Generated by Django 5.2 on 2025-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailotp_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
